### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by rabbittsoup** [hoppscotch/hoppscotch-extension#252]
I'm having trouble reaching a rest API hosted through a special port.  I don't seem to have issues with any hosts that use the expected 80/443 ports.  I'm not sure what the cause is, but the special port is the only thing I can think of that's different from other hosts that work fine.

Example:
GET https://my.host:8081/status

Displays "Could not send request" error page.  The Chrome developer tools console shows:

extension.ts:230 TypeError: Failed to fetch
    at o (chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld/index.js:2:13)
    at N (chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld/index.js:3:1484)
(anonymous) @ console.js:36
runRequestOnExtension @ extension.ts:230

**Comment by liyasthomas** [comment]
Since you're using the browser extension, can you make sure that you've added the origin with port number `https://my.host:8081` to Hoppscotch Browser Extension's origin list?

Documentation: https://docs.hoppscotch.io/documentation/getting-started/setup#locally-served-apis

**Comment by rabbittsoup** [comment]
Thank you for the suggestion.  I see no change in behavior after adding https://my.host:8081 to the origin list of the extension.  To be clear, my.host is a rest API host, not the Hoppscotch web app host.  I am still using the web app from hoppscotch.io.

**Comment by AllenAttuned** [comment]
I'm also getting this error on both Edge (`121.0.2277.106`) and Chrome (`121.0.6167.139`) with the extension version `0.31`. It doesn't happen on Firefox (`122.0`) with version `0.31` of the extension.
